//! Type definitions for the Axum example application.
//!
//! Input types are derived from the `input_schema` in each workflow's task
//! template YAML. They represent the TaskRequest context callers provide.
//!
//! Result types are derived from each step's `result_schema`. They represent
//! what step handlers return and downstream steps consume via dependency injection.
//!
//! Generated by `tasker-ctl generate types`. Each submodule corresponds to one
//! workflow (matching the handler modules).
//!
//! # A note on validation
//!
//! These types use plain `#[derive(Serialize, Deserialize)]` — serde enforces
//! that field types match at deserialization time, but does not validate
//! constraints like "amount must be positive" or "currency must be USD".
//! Doc comments like `/// Allowed values: USD` are informational only and are
//! not enforced at runtime.
//!
//! For production code, consider the [`validator`](https://docs.rs/validator)
//! crate, which adds declarative constraint validation via derive macros:
//!
//! ```rust,ignore
//! use validator::Validate;
//!
//! #[derive(Debug, Serialize, Deserialize, Validate)]
//! pub struct ProcessRefundInput {
//!     #[validate(length(min = 1))]
//!     pub payment_id: String,
//!     #[validate(range(min = 0.01))]
//!     pub refund_amount: f64,
//! }
//!
//! // In handler: returns structured validation errors on bad input
//! let input: ProcessRefundInput = serde_json::from_value(context)?;
//! input.validate().map_err(|e| format!("Validation failed: {e}"))?;
//! ```
//!
//! This cleanly separates structural correctness (serde: "is this valid JSON
//! with the right field types?") from constraint validation (validator: "does
//! the amount meet business rules?"), keeping handler code focused on domain
//! logic rather than defensive checks.

// ============================================================================
// Ecommerce Order Processing
// ============================================================================

pub mod ecommerce {
    use serde::{Deserialize, Serialize};

    // -- Input types (from input_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct OrderProcessingInputCartItems {
        pub product_id: i64,
        pub quantity: i64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct OrderProcessingInput {
        pub cart_items: Vec<OrderProcessingInputCartItems>,
        pub customer_email: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_amount: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_method: Option<String>,
        pub payment_token: String,
    }

    // -- Result types (from result_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ValidateCartResultValidatedItems {
        pub line_total: f64,
        pub name: String,
        pub quantity: i64,
        pub sku: String,
        pub unit_price: f64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ValidateCartResult {
        pub item_count: i64,
        pub shipping: f64,
        pub subtotal: f64,
        pub tax: f64,
        pub tax_rate: f64,
        pub total: f64,
        pub validated_at: String,
        pub validated_items: Vec<ValidateCartResultValidatedItems>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ProcessPaymentResult {
        pub amount_charged: f64,
        pub authorization_code: String,
        /// Allowed values: USD
        pub currency: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_response: Option<String>,
        pub payment_id: String,
        pub payment_method_type: String,
        pub processed_at: String,
        /// Allowed values: completed
        pub status: String,
        pub transaction_id: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdateInventoryResultUpdatedProducts {
        pub new_quantity: i64,
        pub previous_quantity: i64,
        pub product_id: String,
        pub reserved: i64,
        pub sku: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdateInventoryResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub inventory_changes: Option<Vec<serde_json::Value>>,
        pub inventory_log_id: String,
        pub total_items_reserved: i64,
        pub updated_at: String,
        pub updated_products: Vec<UpdateInventoryResultUpdatedProducts>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct CreateOrderResultItems {
        pub line_total: f64,
        pub name: String,
        pub quantity: i64,
        pub sku: String,
        pub unit_price: f64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct CreateOrderResult {
        pub authorization_code: String,
        pub created_at: String,
        pub customer_email: String,
        pub estimated_delivery: String,
        pub inventory_log_id: String,
        pub item_count: i64,
        pub items: Vec<CreateOrderResultItems>,
        pub order_id: String,
        pub order_number: String,
        pub payment_id: String,
        pub shipping: f64,
        /// Allowed values: confirmed
        pub status: String,
        pub subtotal: f64,
        pub tax: f64,
        pub total: f64,
        pub total_amount: f64,
        pub transaction_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub updated_products: Option<Vec<serde_json::Value>>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct SendConfirmationResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub body_preview: Option<String>,
        /// Allowed values: email
        pub channel: String,
        pub email_sent: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub email_type: Option<String>,
        pub message_id: String,
        pub recipient: String,
        pub sent_at: String,
        /// Allowed values: sent
        pub status: String,
        pub subject: String,
        pub template: String,
    }
}

// ============================================================================
// Data Pipeline Analytics
// ============================================================================

pub mod data_pipeline {
    use serde::{Deserialize, Serialize};

    // -- Input types (from input_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct AnalyticsPipelineInputDateRange {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub end_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub start_date: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct AnalyticsPipelineInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub date_range: Option<AnalyticsPipelineInputDateRange>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub pipeline_id: Option<String>,
    }

    // -- Result types (from result_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractSalesDataResultDateRange {
        pub end_date: String,
        pub start_date: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractSalesDataResultRecords {
        pub category: String,
        pub date: String,
        pub product: String,
        pub quantity: i64,
        pub region: String,
        pub total: f64,
        pub unit_price: f64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractSalesDataResult {
        pub date_range: ExtractSalesDataResultDateRange,
        pub extracted_at: String,
        pub record_count: i64,
        pub records: Vec<ExtractSalesDataResultRecords>,
        pub source: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_amount: Option<f64>,
        pub total_quantity: i64,
        pub total_revenue: f64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractInventoryDataResult {
        pub extracted_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub overall_conversion_rate: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub products_tracked: Option<i64>,
        pub record_count: i64,
        pub records: Vec<serde_json::Value>,
        pub source: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_conversions: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_quantity: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_sessions: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub warehouses: Option<Vec<String>>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractCustomerDataResultTierBreakdown {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gold: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub premium: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub standard: Option<i64>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExtractCustomerDataResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avg_lifetime_value: Option<f64>,
        pub extracted_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub low_stock_alerts: Option<i64>,
        pub record_count: i64,
        pub records: Vec<serde_json::Value>,
        pub source: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tier_breakdown: Option<ExtractCustomerDataResultTierBreakdown>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_customers: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_inventory_value: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_lifetime_value: Option<f64>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct TransformSalesResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_category: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_region: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub daily_sales: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub product_sales: Option<serde_json::Value>,
        pub record_count: i64,
        pub records_processed: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub top_category: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_categories: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_regions: Option<i64>,
        pub total_revenue: f64,
        pub transformed_at: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct TransformInventoryResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub best_converting_source: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_page: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_source: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub product_inventory: Option<serde_json::Value>,
        pub record_count: i64,
        pub records_processed: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub reorder_alerts: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_pages: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_quantity_on_hand: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_sources: Option<i64>,
        pub transformed_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub warehouse_summary: Option<serde_json::Value>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct TransformCustomersResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub avg_customer_value: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_category: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub by_warehouse: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub low_stock_count: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub low_stock_items: Option<Vec<serde_json::Value>>,
        pub record_count: i64,
        pub records_processed: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub tier_analysis: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_lifetime_value: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_skus: Option<i64>,
        pub transformed_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub value_segments: Option<serde_json::Value>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct AggregateMetricsResult {
        pub aggregated_at: String,
        pub aggregation_complete: bool,
        pub data_sources: Vec<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub inventory_reorder_alerts: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub inventory_summary: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub inventory_turnover_indicator: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub revenue_per_customer: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub sales_summary: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub sales_transactions: Option<i64>,
        pub sources_included: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_customer_lifetime_value: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_customers: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_inventory_quantity: Option<i64>,
        pub total_records_processed: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_revenue: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub traffic_summary: Option<serde_json::Value>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GenerateInsightsResultHealthScore {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub details: Option<String>,
        pub max_score: i64,
        pub rating: String,
        pub score: i64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GenerateInsightsResultInsights {
        pub message: String,
        pub metric: String,
        pub recommendation: String,
        pub severity: String,
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GenerateInsightsResult {
        pub generated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub health_score: Option<GenerateInsightsResultHealthScore>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub health_status: Option<String>,
        pub insight_count: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub insights: Option<Vec<GenerateInsightsResultInsights>>,
        pub pipeline_complete: bool,
        pub recommendations_count: i64,
        pub total_metrics_analyzed: i64,
    }
}

// ============================================================================
// Microservices User Registration
// ============================================================================

pub mod microservices {
    use serde::{Deserialize, Serialize};

    // -- Input types (from input_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UserRegistrationInput {
        pub email: String,
        pub full_name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub phone: Option<String>,
        /// Allowed values: free, pro, enterprise
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub plan: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
    }

    // -- Result types (from result_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct CreateUserAccountResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub account_status: Option<String>,
        pub created_at: String,
        pub email: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub email_verified: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub full_name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub internal_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub phone: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub plan: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub referral_code: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub source: Option<String>,
        pub status: String,
        pub user_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub username: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub verification_token: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct SetupBillingProfileResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub billing_cycle: Option<String>,
        pub billing_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub billing_required: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub billing_status: Option<String>,
        pub created_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub currency: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub features: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub limits: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub next_billing_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_method_required: Option<bool>,
        /// Allowed values: free, pro, enterprise
        pub plan: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub price: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub pricing: Option<serde_json::Value>,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub subscription_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub trial_end: Option<String>,
        pub user_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub user_internal_id: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct InitializePreferencesResult {
        pub created_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customizations: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub defaults_applied: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub feature_flags: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub notifications: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub onboarding_completed: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub plan: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub preferences: Option<serde_json::Value>,
        pub preferences_id: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub ui_settings: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub updated_at: Option<String>,
        pub user_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub user_internal_id: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct SendWelcomeSequenceResultMessagesSentDetails {
        pub channel: String,
        pub status: String,
        pub template: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct SendWelcomeSequenceResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub channels_used: Option<Vec<String>>,
        pub messages_sent: i64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub messages_sent_details: Option<Vec<SendWelcomeSequenceResultMessagesSentDetails>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub plan: Option<String>,
        pub sent_at: String,
        pub sequence_id: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub total_messages: Option<i64>,
        pub user_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub welcome_sequence_id: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdateUserStatusResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub account_status: Option<String>,
        pub activated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub activation_timestamp: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub all_services_coordinated: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub billing_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub email: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub internal_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub onboarding_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub plan: Option<String>,
        pub registration_complete: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub registration_summary: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub services_completed: Option<Vec<String>>,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub subscription_id: Option<String>,
        pub user_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub welcome_messages_sent: Option<i64>,
    }
}

// ============================================================================
// Customer Success Process Refund
// ============================================================================

pub mod customer_success {
    use serde::{Deserialize, Serialize};

    // -- Input types (from input_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ProcessRefundInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub agent_notes: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub correlation_id: Option<String>,
        pub customer_email: String,
        pub customer_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_id: Option<String>,
        pub refund_amount: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_reason: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub requires_approval: Option<bool>,
        pub ticket_id: String,
    }

    // -- Result types (from result_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ValidateRefundRequestResult {
        pub amount: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_email: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_tier: Option<String>,
        pub eligible: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub order_ref: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub original_purchase_date: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub reason: Option<String>,
        pub request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub request_validated: Option<bool>,
        pub ticket_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub ticket_status: Option<String>,
        pub validated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub validation_hash: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub validation_timestamp: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct CheckRefundPolicyResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub amount_tier: Option<String>,
        /// Allowed values: auto, manager, director
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_path: Option<String>,
        pub checked_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_tier: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub days_since_purchase: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub max_allowed_amount: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub policy_checked: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub policy_checked_at: Option<String>,
        pub policy_compliant: bool,
        pub policy_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub policy_version: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_window_days: Option<i64>,
        pub request_id: String,
        pub requires_approval: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub requires_review: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub rules_applied: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub within_refund_window: Option<bool>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GetManagerApprovalResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub amount_approved: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_note: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_obtained: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_path: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approval_required: Option<bool>,
        pub approved: bool,
        pub approved_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub approver: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub auto_approved: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub manager_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub manager_notes: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        pub request_id: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ExecuteRefundWorkflowResult {
        pub amount_refunded: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub correlation_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub currency: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub delegated_task_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub delegated_task_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub delegation_timestamp: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub estimated_arrival: Option<String>,
        pub executed_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub order_ref: Option<String>,
        pub refund_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_method: Option<String>,
        pub request_id: String,
        /// Allowed values: completed, processing
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub target_namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub target_workflow: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub task_delegated: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub transaction_ref: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdateTicketStatusResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub amount_refunded: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_notified: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub delegated_task_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        pub new_status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub notification_channel: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub previous_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_completed: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_id: Option<String>,
        pub request_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub resolution: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub resolution_note: Option<String>,
        pub resolved_at: String,
        pub ticket_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub ticket_status: Option<String>,
        pub ticket_updated: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub updated_at: Option<String>,
    }
}

// ============================================================================
// Payments Process Refund
// ============================================================================

pub mod payments {
    use serde::{Deserialize, Serialize};

    // -- Input types (from input_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ProcessRefundInput {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub correlation_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_email: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub partial_refund: Option<bool>,
        pub payment_id: String,
        pub refund_amount: f64,
        /// Allowed values: customer_request, fraud, system_error, chargeback
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_reason: Option<String>,
    }

    // -- Result types (from result_schema) --

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ValidatePaymentEligibilityResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub amount: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_email: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub eligibility_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub eligibility_status: Option<String>,
        pub eligible: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub fraud_flagged: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub fraud_score: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_provider: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        pub order_ref: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub original_amount: Option<f64>,
        pub payment_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_method: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_validated: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub reason: Option<String>,
        pub refund_amount: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_percentage: Option<f64>,
        pub validated_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub validation_timestamp: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub within_refund_window: Option<bool>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ProcessGatewayRefundResult {
        pub amount_processed: f64,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub authorization_code: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub currency: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub estimated_arrival: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_provider: Option<String>,
        pub gateway_status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_transaction_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_txn_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub order_ref: Option<String>,
        pub payment_id: String,
        pub processed_at: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub processor_message: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub processor_response_code: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_amount: Option<f64>,
        pub refund_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_processed: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub settlement_batch: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub settlement_id: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdatePaymentRecordsResultLedgerEntries {
        pub amount: f64,
        pub currency: String,
        pub timestamp: String,
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct UpdatePaymentRecordsResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub amount_recorded: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub fiscal_period: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub gateway_txn_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub history_entries_created: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub journal_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub ledger_entries: Option<Vec<UpdatePaymentRecordsResultLedgerEntries>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub order_ref: Option<String>,
        pub payment_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub payment_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub reconciliation_status: Option<String>,
        pub record_id: String,
        pub recorded_at: String,
        pub records_updated: bool,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_status: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub updated_at: Option<String>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct NotifyCustomerResult {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub body_preview: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub channel: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub customer_email: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub delivery_status: Option<String>,
        pub message_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub namespace: Option<String>,
        pub notification_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub notification_sent: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub notification_type: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub recipient: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub references: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_amount: Option<f64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub refund_id: Option<String>,
        pub sent_at: String,
        pub status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub subject: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub template: Option<String>,
    }
}
