name: Setup sccache
description: Configure sccache for faster Rust builds in GitHub Actions

runs:
  using: composite
  steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Configure sccache environment
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
        echo "CARGO_TERM_COLOR=always" >> "$GITHUB_ENV"
