source 'https://rubygems.org'

ruby '>= 3.1'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'tasker-rb', '~> 0.1.1'
gem 'dotenv-rails', '~> 3.1'
gem 'puma', '~> 6.4'

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
end

group :test do
  gem 'factory_bot_rails', '~> 6.4'
end
