source 'https://rubygems.org'

ruby '>= 3.1'

gem 'rails', '~> 8.0'
gem 'pg', '~> 1.5'
# Use local tasker-rb from tasker-core workspace (native extension pre-built)
# In production/CI, switch to: gem 'tasker-rb', '~> 0.1.1'
gem 'tasker-rb', '~> 0.1.3'
# dotenv ~> 2.8 is pulled in by tasker-rb; load manually in config/application.rb
gem 'puma', '~> 6.4'

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
end

group :test do
  gem 'factory_bot_rails', '~> 6.4'
end
